[profile.default]
src = "."
out = "out"
cache_path = "cache"
libs = ["lib"]
exclude = ["verifier", "reldo-vesting"]
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
base = "https://mainnet.base.org"

[etherscan]
base = { key = "${ETHERSCAN_API_KEY}", url = "https://api.basescan.org/api", chain = 8453 }
